from dotenv import load_dotenv
from openai import OpenAI
import click
from rich.console import Console
from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory
import os

load_dotenv()
DEFAULT_MODEL = os.environ["OPENAI_MODEL"]
console = Console()

# Create a prompt session that saves history to a file
prompt_session = PromptSession(history=FileHistory('.prompt_history'))

def build_client() -> OpenAI:
    load_dotenv()
    return OpenAI()


"""
A message input to the model with a role indicating instruction following hierarchy. 
Instructions given with the developer or system role take precedence over instructions 
given with the user role. Messages with the assistant role are presumed to have
been generated by the model in previous interactions.
"""
def create_conversation(client: OpenAI, system_prompt: str):
    return client.conversations.create(
        metadata={"topic": "interactive-conversation-demo"},
        items=[
            {
                "role": "developer",
                "content": system_prompt
            }
        ]
    )


def extract_text(item) -> str:
    content = getattr(item, "content", None)
    if content:
        parts = []
        for chunk in content:
            text = getattr(chunk, "text", None)
            if text is None and isinstance(chunk, dict):
                text = chunk.get("text")
            if text:
                parts.append(text)
        if parts:
            return " ".join(parts)

    return getattr(item, "output_text", None) or getattr(item, "input_text", None) or ""

def get_history(client: OpenAI, conversation_id: str) -> list:
    pages = []
    page = client.conversations.items.list(conversation_id=conversation_id, limit=100, order="asc")
    pages.append(page)
    while page.data:
        if not getattr(page, "has_more", False) or not getattr(page, "last_id", None):
            break
        page = client.conversations.items.list(
            conversation_id=conversation_id,
            after=page.last_id,
            limit=100,
            order="asc",
        )
        pages.append(page)
    return pages

def print_history(client: OpenAI, conversation_id: str) -> None:
    click.echo(f"\nConversation history for {conversation_id}:")
    pages = get_history(client, conversation_id)
    turn_number = 1
    for page in pages:
        for item in page.data:
            role = getattr(item, "role", None)
            if role not in {"user", "assistant"}:
                continue
            text = extract_text(item)
            if not text:
                continue
            label = f"{role.capitalize()} {turn_number}"
            click.echo(f"- {label}: {text}")
            if role == "assistant":
                turn_number += 1

def get_total_character_length(client: OpenAI, conversation_id: str) -> int:
    items_page = client.conversations.items.list(conversation_id=conversation_id, limit=100)
    total_chars = 0
    for item in items_page.data:
        text = extract_text(item)  # using your extract_text helper
        total_chars += len(text)
    return total_chars

def ask_until_exit() -> str:
    while True:
        try:
            text = prompt_session.prompt("You >>> ").strip()
            if text:
                return text
        except (click.Abort, KeyboardInterrupt):
            return "/exit"


def print_system_prompt(client: OpenAI, conversation_id:str) -> None:
    # Verify developer/system prompt exists in conversation history
    items = client.conversations.items.list(conversation_id=conversation_id)
    for item in items.data:
        if getattr(item, "role", None) in {"developer", "system"}:
            print("System prompt successfully set:", extract_text(item))


@click.command()
@click.option("--model", default=DEFAULT_MODEL, show_default=True, help="OpenAI model to use.")
@click.option("--system", "system_prompt",
              default="You are a helpful, concise IT support assistant working inside a enterprise environment. "
                      "Keep you answer short, less commentary.",
              show_default=True,
              help="Instructions for the assistant.")
@click.option("--temperature", default=0.0, show_default=True, help="Model temperature.", type=float)
def main(model: str, system_prompt: str, temperature:float) -> None:
    client = build_client()
    conversation = create_conversation(client, system_prompt)

    click.echo("Interactive OpenAI conversation")
    click.echo(f"Conversation ID: {conversation.id}")
    click.echo("Type /history to print the stored transcript, or /exit to quit.\n")

    print_system_prompt(client, conversation.id)

    while True:
        user_text = ask_until_exit()
        if user_text.lower() in {"/exit", "exit", "quit"}:
            break
        if user_text.lower() == "/history":
            print_history(client, conversation.id)
            continue

        with console.status("[bold green]Assistant is thinking...", spinner="dots"):
            response = client.responses.create(
                model=model,
                conversation={"id": conversation.id},
                instructions=system_prompt,
                input=user_text,
                # Use store: true to maintain state from turn to turn,
                # preserving reasoning and tool context from turn-to-turn.
                store=True,
                context_management = [
                    {"type": "compaction", "compact_threshold": 2000}
                ],
                truncation = "auto",
                temperature = 0.0
            )
            click.echo(f"\nAssistant >>> {response.output_text}\n")

if __name__ == "__main__":
    main()
